# Generated by Django 5.2.12 on 2026-04-09 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_alter_sport_created_at_alter_usersport_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 50, 22, 37409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usersport',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 50, 22, 37409, tzinfo=datetime.timezone.utc)),
        ),
    ]
