# Generated by Django 5.2.12 on 2026-04-09 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0008_alter_sport_created_at_alter_usersport_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
