# Generated by Django 5.2.12 on 2026-04-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_alter_sport_created_at_alter_usersport_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
