"""complete_train_schema

Revision ID: 5b19c8827569
Revises: 
Create Date: 2026-04-29 17:00:19.151759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b19c8827569'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_session',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('planned_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_training_session_profile_id'), 'training_session', ['profile_id'], unique=False, schema='train')
    op.create_index(op.f('ix_train_training_session_sport_id'), 'training_session', ['sport_id'], unique=False, schema='train')
    op.create_table('training_session_block',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['train.training_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_training_session_block_session_id'), 'training_session_block', ['session_id'], unique=False, schema='train')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_training_session_block_session_id'), table_name='training_session_block', schema='train')
    op.drop_table('training_session_block', schema='train')
    op.drop_index(op.f('ix_train_training_session_sport_id'), table_name='training_session', schema='train')
    op.drop_index(op.f('ix_train_training_session_profile_id'), table_name='training_session', schema='train')
    op.drop_table('training_session', schema='train')
    # ### end Alembic commands ###
