"""add_columns_to_training_session_block

Revision ID: edb8199edb11
Revises: 5b19c8827569
Create Date: 2026-04-30 15:59:15.509797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb8199edb11'
down_revision: Union[str, Sequence[str], None] = '5b19c8827569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_goal',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.String(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_athlete_goal_profile_id'), 'athlete_goal', ['profile_id'], unique=False, schema='train')
    op.create_index(op.f('ix_train_athlete_goal_sport_id'), 'athlete_goal', ['sport_id'], unique=False, schema='train')
    op.create_table('athlete_health_profile',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_athlete_health_profile_profile_id'), 'athlete_health_profile', ['profile_id'], unique=False, schema='train')
    op.create_table('athlete_profile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_athlete_profile_user_id'), 'athlete_profile', ['user_id'], unique=False, schema='train')
    op.create_table('athlete_training_structure',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.String(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_athlete_training_structure_profile_id'), 'athlete_training_structure', ['profile_id'], unique=False, schema='train')
    op.create_index(op.f('ix_train_athlete_training_structure_sport_id'), 'athlete_training_structure', ['sport_id'], unique=False, schema='train')
    op.create_table('test_template',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_test_template_code'), 'test_template', ['code'], unique=True, schema='train')
    op.create_index(op.f('ix_train_test_template_level'), 'test_template', ['level'], unique=False, schema='train')
    op.create_index(op.f('ix_train_test_template_sport'), 'test_template', ['sport'], unique=False, schema='train')
    op.create_table('training_session',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('planned_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_training_session_profile_id'), 'training_session', ['profile_id'], unique=False, schema='train')
    op.create_index(op.f('ix_train_training_session_sport_id'), 'training_session', ['sport_id'], unique=False, schema='train')
    op.create_table('athlete_goal_value',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['train.athlete_goal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_athlete_goal_value_goal_id'), 'athlete_goal_value', ['goal_id'], unique=False, schema='train')
    op.create_table('athlete_health_profile_value',
    sa.Column('health_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['health_id'], ['train.athlete_health_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_athlete_health_profile_value_health_id'), 'athlete_health_profile_value', ['health_id'], unique=False, schema='train')
    op.create_table('athlete_profile_value',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['train.athlete_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_athlete_profile_value_profile_id'), 'athlete_profile_value', ['profile_id'], unique=False, schema='train')
    op.create_table('athlete_sport_profile',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.String(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['train.athlete_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_athlete_sport_profile_profile_id'), 'athlete_sport_profile', ['profile_id'], unique=False, schema='train')
    op.create_index(op.f('ix_train_athlete_sport_profile_sport_id'), 'athlete_sport_profile', ['sport_id'], unique=False, schema='train')
    op.create_table('athlete_training_structure_value',
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['train.athlete_training_structure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_athlete_training_structure_value_structure_id'), 'athlete_training_structure_value', ['structure_id'], unique=False, schema='train')
    op.create_table('test_template_block',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('block_order', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.String(length=20), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['train.test_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_test_template_block_template_id'), 'test_template_block', ['template_id'], unique=False, schema='train')
    op.create_table('training_session_block',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.String(length=20), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['train.training_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_training_session_block_session_id'), 'training_session_block', ['session_id'], unique=False, schema='train')
    op.create_table('athlete_sport_profile_value',
    sa.Column('sport_profile_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sport_profile_id'], ['train.athlete_sport_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='train'
    )
    op.create_index(op.f('ix_train_athlete_sport_profile_value_sport_profile_id'), 'athlete_sport_profile_value', ['sport_profile_id'], unique=False, schema='train')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_athlete_sport_profile_value_sport_profile_id'), table_name='athlete_sport_profile_value', schema='train')
    op.drop_table('athlete_sport_profile_value', schema='train')
    op.drop_index(op.f('ix_train_training_session_block_session_id'), table_name='training_session_block', schema='train')
    op.drop_table('training_session_block', schema='train')
    op.drop_index(op.f('ix_train_test_template_block_template_id'), table_name='test_template_block', schema='train')
    op.drop_table('test_template_block', schema='train')
    op.drop_index(op.f('ix_train_athlete_training_structure_value_structure_id'), table_name='athlete_training_structure_value', schema='train')
    op.drop_table('athlete_training_structure_value', schema='train')
    op.drop_index(op.f('ix_train_athlete_sport_profile_sport_id'), table_name='athlete_sport_profile', schema='train')
    op.drop_index(op.f('ix_train_athlete_sport_profile_profile_id'), table_name='athlete_sport_profile', schema='train')
    op.drop_table('athlete_sport_profile', schema='train')
    op.drop_index(op.f('ix_train_athlete_profile_value_profile_id'), table_name='athlete_profile_value', schema='train')
    op.drop_table('athlete_profile_value', schema='train')
    op.drop_index(op.f('ix_train_athlete_health_profile_value_health_id'), table_name='athlete_health_profile_value', schema='train')
    op.drop_table('athlete_health_profile_value', schema='train')
    op.drop_index(op.f('ix_train_athlete_goal_value_goal_id'), table_name='athlete_goal_value', schema='train')
    op.drop_table('athlete_goal_value', schema='train')
    op.drop_index(op.f('ix_train_training_session_sport_id'), table_name='training_session', schema='train')
    op.drop_index(op.f('ix_train_training_session_profile_id'), table_name='training_session', schema='train')
    op.drop_table('training_session', schema='train')
    op.drop_index(op.f('ix_train_test_template_sport'), table_name='test_template', schema='train')
    op.drop_index(op.f('ix_train_test_template_level'), table_name='test_template', schema='train')
    op.drop_index(op.f('ix_train_test_template_code'), table_name='test_template', schema='train')
    op.drop_table('test_template', schema='train')
    op.drop_index(op.f('ix_train_athlete_training_structure_sport_id'), table_name='athlete_training_structure', schema='train')
    op.drop_index(op.f('ix_train_athlete_training_structure_profile_id'), table_name='athlete_training_structure', schema='train')
    op.drop_table('athlete_training_structure', schema='train')
    op.drop_index(op.f('ix_train_athlete_profile_user_id'), table_name='athlete_profile', schema='train')
    op.drop_table('athlete_profile', schema='train')
    op.drop_index(op.f('ix_train_athlete_health_profile_profile_id'), table_name='athlete_health_profile', schema='train')
    op.drop_table('athlete_health_profile', schema='train')
    op.drop_index(op.f('ix_train_athlete_goal_sport_id'), table_name='athlete_goal', schema='train')
    op.drop_index(op.f('ix_train_athlete_goal_profile_id'), table_name='athlete_goal', schema='train')
    op.drop_table('athlete_goal', schema='train')
    # ### end Alembic commands ###
