# Generated by Django 6.0.3 on 2026-04-14 12:29

from django.db import migrations


def create_initial_data(apps, _):
    Role = apps.get_model('permissions', 'Role')

    Role.objects.get_or_create(name='Admin', code='admin')
    Role.objects.get_or_create(name='Coach', code='coach')
    Role.objects.get_or_create(name='Athlete', code='athlete')

class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_userrole'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
