# Generated by Django 5.2.12 on 2026-04-08 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_alter_permission_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permission',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
