# Generated by Django 5.2.12 on 2026-04-09 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0008_alter_permission_created_at_alter_role_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 48, 48, 912466, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 48, 48, 912466, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 48, 48, 912466, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 48, 48, 912466, tzinfo=datetime.timezone.utc)),
        ),
    ]
