# Generated by Django 6.0.3 on 2026-04-13 20:01

from django.db import migrations



def create_initial_data(apps, _):
    Module = apps.get_model('modules', 'Module')

    Module.objects.get_or_create(name='Core', code='code')
    Module.objects.get_or_create(name='Train', code='train')
    Module.objects.get_or_create(name='Events', code='events')
    Module.objects.get_or_create(name='Arena', code='arena')
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
