# Generated by Django 5.2.12 on 2026-04-09 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_module_created_at_alter_module_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 35, 2, 948622, tzinfo=datetime.timezone.utc)),
        ),
    ]
