# Generated by Django 5.2.12 on 2026-03-23 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('plans', '0006_planmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='module',
            field=models.ForeignKey(default='70edeb58-7ca8-4cc8-a4d4-2b2fc479462f', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='modules.module'),
            preserve_default=False,
        ),
    ]
