# Generated by Django 5.2.12 on 2026-04-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_planform'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
    ]
