# Generated by Django 5.2.12 on 2026-04-08 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_userplan_auto_renew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 22, 22, 8, 925712, tzinfo=datetime.timezone.utc)),
        ),
    ]
