# Generated by Django 5.2.12 on 2026-04-08 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_alter_userplan_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 49, 12, 450537, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='feature',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 49, 12, 450537, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 49, 12, 450537, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='planform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 49, 12, 450537, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='planform',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='planmodule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 49, 12, 450537, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='planmodule',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 49, 12, 450537, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 49, 12, 450537, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
