# Generated by Django 5.2.12 on 2026-04-08 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_alter_feature_created_at_alter_feature_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='feature',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='planform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='planform',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='planmodule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='planmodule',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
