# Generated by Django 5.2.12 on 2026-04-09 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_alter_feature_created_at_alter_feature_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 35, 2, 948622, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 35, 2, 948622, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 35, 2, 948622, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='planform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 35, 2, 948622, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='planmodule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 35, 2, 948622, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 35, 2, 948622, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 35, 2, 948622, tzinfo=datetime.timezone.utc)),
        ),
    ]
