# Generated by Django 5.2.12 on 2026-04-09 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_alter_feature_created_at_alter_plan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 50, 22, 37409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 50, 22, 37409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 50, 22, 37409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='planform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 50, 22, 37409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='planmodule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 50, 22, 37409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 50, 22, 37409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 50, 22, 37409, tzinfo=datetime.timezone.utc)),
        ),
    ]
