# Generated by Django 5.2.12 on 2026-04-09 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0017_alter_feature_created_at_alter_plan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
