# Generated by Django 5.2.12 on 2026-04-09 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_created_at_alter_profile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 35, 2, 948622, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profiletype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 35, 2, 948622, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 35, 2, 948622, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 15, 35, 2, 948622, tzinfo=datetime.timezone.utc)),
        ),
    ]
