# Generated by Django 5.2.12 on 2026-03-24 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_sportform'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='modules.module'),
        ),
    ]
