# Generated by Django 5.2.12 on 2026-03-31 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_fieldtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='type',
        ),
        migrations.AddField(
            model_name='field',
            name='data_type',
            field=models.ForeignKey(default='be8ec113-4965-4da7-972a-757ac2b72dc2', on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='forms.datatype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='field_type',
            field=models.ForeignKey(default='bf5c326d-5912-4c56-9e6b-df564c33f94f', on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='forms.fieldtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
