# Generated by Django 5.2.12 on 2026-03-31 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_fieldoption'),
        ('sports', '0002_usersport'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='label',
            field=models.CharField(default='text', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formfield',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='sports.sport'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('form', 'field', 'sport')},
        ),
    ]
