# Generated by Django 5.2.12 on 2026-03-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_formfield_label_formfield_sport_and_more'),
        ('sports', '0002_usersport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sportform',
            unique_together={('sport', 'form')},
        ),
    ]
