# Generated by Django 5.2.12 on 2026-04-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_alter_sportform_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldoption',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
