# Generated by Django 5.2.12 on 2026-04-02 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_fieldoption_order'),
        ('sports', '0002_usersport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('form', 'field', 'sport'), name='unique_form_field_sport'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('order', 'field'), name='unique_order_field'),
        ),
    ]
