# Generated by Django 5.2.12 on 2026-04-08 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_alter_datatype_created_at_alter_datatype_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='field',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='form',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sportfield',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sportfield',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sportform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 23, 51, 23, 275548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sportform',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
