# Generated by Django 5.2.12 on 2026-04-09 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_alter_datatype_created_at_alter_field_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 49, 12, 227014, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 49, 12, 227014, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 49, 12, 227014, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 49, 12, 227014, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 49, 12, 227014, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 49, 12, 227014, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sportfield',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 49, 12, 227014, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sportform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 16, 49, 12, 227014, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='form',
            table=None,
        ),
    ]
