# Generated by Django 5.2.12 on 2026-05-04 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_alter_datatype_created_at_alter_field_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='forms.datatype'),
        ),
    ]
