# Generated by Django 5.2.12 on 2026-05-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_alter_field_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='ui_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
